### ISSUE TITLE
Make the chat screen responsive

### ISSUE THREAD

**Issue by Abdul-Muiz-Iqbal** [Abdul-Muiz-Iqbal/PostMan#2]
We could use the flex property in order to determine the size of the chat-pane and member-pane.

Best to look at WhatsApp Web's implementation.

**Comment by Abdul-Muiz-Iqbal** [comment]
We have decided to use Kivy for the Gui due to the fact that it will allow us to create an Android version on PostMan on our existing codebase.

**Comment by aleeazam** [comment]
Who else is contributing to the project?

Kivy looks pretty antiquated in it's vanilla form. Hope you are customizing it heavily, and it turns out looking fine.

**Comment by aleeazam** [comment]
Also, when's the CLI version going to roll out?

I feel like you aren't testing PMan with multiple users/devices enough.

**Comment by aleeazam** [comment]
Also also, use Google Groups for this sort of discussion.

**Comment by aleeazam** [comment]
Internal comms resulted in switching to **eel**. I guess this issue should be closed after all.

**Comment by Abdul-Muiz-Iqbal** [comment]
No one else. Kivy is out of question now, it doesn't work on my machine. No CLI version, back to eel, so I gotta reopen this.

**Comment by Abdul-Muiz-Iqbal** [comment]
Fixed in commit.
